# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum_portrait_vfhq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum_portrait_vfhq.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19\x64\x61tum_portrait_vfhq.proto\"\x86\x01\n\nDatum_vfhq\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0b\n\x03num\x18\x04 \x01(\x05\x12\x0e\n\x06images\x18\x05 \x01(\x0c\x12\x0c\n\x04segs\x18\x06 \x01(\x0c\x12\x0e\n\x06labels\x18\x07 \x01(\x0c\x12\x0c\n\x04mots\x18\x08 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATUM_VFHQ = _descriptor.Descriptor(
  name='Datum_vfhq',
  full_name='Datum_vfhq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='Datum_vfhq.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='Datum_vfhq.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='Datum_vfhq.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='Datum_vfhq.num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='images', full_name='Datum_vfhq.images', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segs', full_name='Datum_vfhq.segs', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels', full_name='Datum_vfhq.labels', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mots', full_name='Datum_vfhq.mots', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['Datum_vfhq'] = _DATUM_VFHQ

Datum_vfhq = _reflection.GeneratedProtocolMessageType('Datum_vfhq', (_message.Message,), dict(
  DESCRIPTOR = _DATUM_VFHQ,
  __module__ = 'datum_portrait_vfhq_pb2'
  # @@protoc_insertion_point(class_scope:Datum_vfhq)
  ))
_sym_db.RegisterMessage(Datum_vfhq)


# @@protoc_insertion_point(module_scope)
