# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datum_genhead.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datum_genhead.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x64\x61tum_genhead.proto\"z\n\rDatum_genhead\x12\x10\n\x08\x63hannels\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\x12\x0b\n\x03seg\x18\x05 \x01(\x0c\x12\x0e\n\x06labels\x18\x06 \x01(\x0c\x12\x0c\n\x04mots\x18\x07 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATUM_GENHEAD = _descriptor.Descriptor(
  name='Datum_genhead',
  full_name='Datum_genhead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channels', full_name='Datum_genhead.channels', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='Datum_genhead.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='Datum_genhead.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='Datum_genhead.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seg', full_name='Datum_genhead.seg', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels', full_name='Datum_genhead.labels', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mots', full_name='Datum_genhead.mots', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['Datum_genhead'] = _DATUM_GENHEAD

Datum_genhead = _reflection.GeneratedProtocolMessageType('Datum_genhead', (_message.Message,), dict(
  DESCRIPTOR = _DATUM_GENHEAD,
  __module__ = 'datum_genhead_pb2'
  # @@protoc_insertion_point(class_scope:Datum_genhead)
  ))
_sym_db.RegisterMessage(Datum_genhead)


# @@protoc_insertion_point(module_scope)
